[package]
name = "slider-puzzle"
version = "0.1.0"
authors = ["mbarszcz"]
edition = "2018"

[lib]
name = "slider_solver_lib"
path = "src/lib.rs"

[[bin]]
name = "slider_solver"
path = "src/main.rs"

[dependencies]
priority-queue = "1.0.5"
